---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  containers:
    - name: helloworld
      image: todddsm/hello-world:latest
      imagePullPolicy: IfNotPresent
      command: [ "echo", "SUCCESS" ]
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: helloworld
  type: LoadBalancer