apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  clusterIP: 10.103.67.70
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31591
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: hello-world
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
